project:
  type: website

website:
  title: "SelianBlog"
  description: "A blog built with Quarto"
  site-url: https://selianu.github.io/SelianBlog
  favicon: favicon.ico
  open-graph: true
  navbar:
    left:
      - text: "Posts"
        href: posts.qmd
      - text: "Reviews"
        href: reviews.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/SelianU

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    highlight-style: nord
    code-fold: true
    toc: true
    html-math-method: mathjax
    include-in-header:
      text: |
        <script>
        MathJax = {
          tex: {
            inlineMath: [["$", "$"], ["\\(", "\\)"]],
            displayMath: [["$$", "$$"], ["\\[", "\\]"]],
          },
        };
        </script>
        <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js"></script>
    filters:
      - leovan/pseudocode

pseudocode:
  caption-prefix: "Algorithm"
  reference-prefix: "Algorithm"
  caption-number: true
  caption-align: "left"