project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://selianu.github.io/SelianBlog
  title: "SelianBlog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/SelianU
      - icon: bluesky
        href: https://bsky.app/
    left:
      - text: "Posts"
        href: index.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



